"""create gas tables

Revision ID: 101a31284be1
Revises: 
Create Date: 2026-09-14 16:19:58.517861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101a31284be1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_table('gases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_name', sa.String(length=100), nullable=False),
    sa.Column('gas_formula', sa.String(length=20), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('gas_status', sa.String(length=20), nullable=False),
    sa.Column('gas_image_url', sa.String(length=255), nullable=True),
    sa.Column('gas_video_url', sa.String(length=255), nullable=True),
    sa.Column('molar_mass', sa.Float(), nullable=True),
    sa.Column('density_normal_conditions', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('formed_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gases_id'), 'gases', ['id'], unique=False)
    op.create_table('gas_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gas_id'], ['gases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_likes_id'), 'gas_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gas_likes_id'), table_name='gas_likes')
    op.drop_table('gas_likes')
    op.drop_index(op.f('ix_gases_id'), table_name='gases')
    op.drop_table('gases')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
